name: image
description: Build image and push to Docker Hub and GitHib Container Registry
author: hyperbola

inputs:
  init:
    description: Setup QEMU, buildx and logins
    required: false
    default: 'true'
  dockerhub:
    description: push image to dockerhub
    required: false
    default: 'true'
  ghcr:
    description: push image to ghcr.io
    required: false
    default: 'true'
  dockerhub-username:
    description: dockerhub username
    required: false
  dockerhub-password:
    description: dockerhub API token
    required: false
  image:
    description: name of image
    required: false
  latest:
    description: push image with tag `latest`
    required: false
    default: 'false'
  github-token:
    description: github token used to push image to ghcr
    required: false
  platforms:
    description: platform list to build image
    required: false
    default: linux/amd64,linux/arm64
  build-target:
    description: target stage to build
    required: false

runs:
  using: composite
  steps:
    - name: Get project version
      id: version
      uses: wdzeng/version@v1
      with:
        prefix: ''
    - name: Determine Dockerhub image names
      id: dockerhub-tags
      if: ${{ inputs.dockerhub == 'true' }}
      shell: bash -e {0}
      run: |
        USR="${{ inputs.dockerhub-username }}"
        USR="${USR:-${{ github.repository_owner }}}"
        echo ::debug::username=$USR

        IMG="${{ inputs.image }}"
        REPO_NAME=${{ github.repository }}
        IMG="${IMG:-${REPO_NAME#*/}}"
        echo ::debug::image=$IMG

        TAGS="$USR/$IMG:$VER,$USR/$IMG:$VER_MIN,$USR/$IMG:$VER_MAJ"
        if [[ '${{ inputs.latest }}' == 'true' ]]; then TAGS="$TAGS,$USR/$IMG:latest"; fi
        echo ::set-output name=tags::$TAGS
    - name: Determine ghcr image names
      if: ${{ inputs.ghcr == 'true' }}
      id: ghcr-tags
      env:
        VER: ${{ steps.version.outputs.version }}
        VER_MIN: ${{ steps.version.outputs.minor }}
        VER_MAJ: ${{ steps.version.outputs.major }}
      shell: bash -e {0}
      run: |
        USR="${{ github.repository_owner }}"
        echo ::debug::username=$USR

        IMG="${{ inputs.image }}"
        REPO_NAME=${{ github.repository }}
        IMG="${IMG:-${REPO_NAME#*/}}"
        echo ::debug::image=$IMG

        DOM='ghcr.io'

        TAGS="$DOM/$USR/$IMG:$VER,$DOM/$USR/$IMG:$VER_MIN,$DOM/$USR/$IMG:$VER_MAJ"
        if [[ '${{ inputs.latest }}' == 'true' ]]; then TAGS="$TAGS,$DOM/$USR/$IMG:latest"; fi
        echo ::set-output name=tags::$TAGS
    - name: Set up QEMU
      if: ${{ inputs.init == 'true' }}
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      if: ${{ inputs.init == 'true' }}
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      if: ${{ inputs.dockerhub == 'true' && inputs.init == 'true' }}
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}
    - name: Login to ghcr
      if: ${{ inputs.ghcr == 'true' && inputs.init == 'true' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token || github.token }}
    - name: Get current timestamp
      id: date
      shell: bash -e {0}
      run: |
        now=$(TZ=Asia/Taipei date -Is)
        echo ::set-output name=now::$now
    - name: Build image and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: ${{ inputs.platforms }}
        target: ${{ inputs.build-target }}
        labels: |
          org.opencontainers.image.title="${{ github.event.repository.name }}"
          org.opencontainers.image.version="${{ steps.version.outputs.version }}"
          org.opencontainers.image.authors="hyperbola <me@hyperbola.me>"
          org.opencontainers.image.url="https://github.com/${{ github.repository }}"
          org.opencontainers.image.source="https://github.com/${{ github.repository }}"
          org.opencontainers.image.created="${{ steps.date.outputs.now }}"
          org.opencontainers.image.documentation="https://github.com/${{ github.repository }}/blob/master/README.md"
          org.opencontainers.image.revision="${{ github.sha }}"
